### ISSUE TITLE
plugin.yml missing

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/InteractiveMessenger#11]
Hi, plugin.yml is missing in the latest build? Tried to add it to the server and it failed to load.

Thanks  :)

**Comment by NLthijs48** [comment]
This is a library to be used in plugins, it is not a plugin itself. For example AreaShop uses this library for its customizable language files, it embeds the code of this library (which means you don't have to install this separately).

The jar files are build on Jenkins because I publish them to a Maven repository with that, so that AreaShop and other plugins can easily include it.

There is a maven build flag to create a jar you can add to your server, but that is purely for testing a list of messages to see if they are displayed in the Minecraft client as intended, which is probably not what you are looking for right?

**Comment by frizzbee30** [comment]
Hi, thanks for the reply, it explains it perfectly (as expected), much appreciated  :)
